name: tenor_dart
description: A client for interacting with the Tenor API directly in Dart. Supports all the major endpoints such as featured (trending), search, categories, etc.
version: 0.0.1
homepage: https://github.com/flyclops/tenor_dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  test: ^1.25.2
