name: tenor_dart
version: 0.0.2
description: "A client for interacting with the Tenor API directly in Dart. Supports all the major endpoints such as featured (trending), search, categories, etc."
homepage: https://github.com/flyclops
repository: https://github.com/flyclops/tenor_dart
screenshots:
  - description: "Browsing featured gifs from Tenor"
    path: example/assets/demo.gif
topics:
  - gif
  - tenor

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^1.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.2
