name: tenor_dart
description: A client for interacting with the Tenor API directly in Dart. Supports all the major endpoints such as featured (trending), search, categories, etc.
version: 0.0.1
homepage: https://github.com/flyclops/tenor_dart

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_analysis_options:
    git:
      url: https://github.com/Flyclops/dart_analysis_options.git
      ref: v0.0.1
  json_serializable: ^6.8.0

flutter:
  # Run this command to create the generated files: "dart pub run build_runner build --delete-conflicting-outputs"
  generate: false
